[workspace]
resolver = "2"

members = [
    "libinitia",
    "crates/compiler",
    "crates/gas",
    "crates/natives",
    "crates/vm",
    "crates/types",
    "crates/storage",
    "crates/e2e-move-tests",
    "tools/generate-bcs-go",
    "tools/precompile",
]
exclude = []

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true
strip = "debuginfo"

[profile.bench]
debug = true

[profile.dev]
debug = true

# use release settings to reduce memory pressure in the linking step in CI
[profile.ci]
inherits = "test"
opt-level = 3
debug = 0           # for saving disk space during linking
incremental = false
codegen-units = 16

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BUSL-1.1"
homepage = "https://www.initia.co"
repository = "https://github.com/initia-labs/initiavm/"
rust-version = "1.76.0"

[workspace.dependencies]
# Internal crate dependencies.
# Please do not add any test features here: they should be declared by the individual crate.
initia = { path = "libinitia" }
initia-vm = { path = "crates/vm" }
initia-types = { path = "crates/types" }
initia-storage = { path = "crates/storage" }
initia-natives = { path = "crates/natives" }
initia-gas = { path = "crates/gas" }
initia-compiler = { path = "crates/compiler" }

# External crate dependencies.
# Please do not add any test features here: they should be declared by the individual crate.
anyhow = "1.0.41"
bcs = "0.1.5"
better_any = "0.1.1"
clru = "0.6"
cbindgen = "0.26.0"
clap = { version = "4.3.9", features = ["derive", "env", "suggestions"] }
codespan-reporting = "0.11.1"
dialoguer = "0.10.2"
ed25519-consensus = { version = "2.0.1", features = ["serde"] }
errno = "0.3.0"
hex = { version = "0.4.3", default-features = false }
itertools = "0.10.3"
libsecp256k1 = { version = "0.7.1" }
log = { version = "0.4.17", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
once_cell = "1.18.0"
rand = "0.8.5"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.188", default-features = false, features = [
    "derive",
    "rc",
] }
serde_bytes = "0.11.9"
serde_json = { version = "1.0.94" }
serde-generate = { git = "https://github.com/aptos-labs/serde-reflection", rev = "73b6bbf748334b71ff6d7d09d06a29e3062ca075" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "73b6bbf748334b71ff6d7d09d06a29e3062ca075" }
sha3 = "0.10.6"
smallvec = "1.6.1"
tempfile = "3.2.0"
serial_test = "1.0.0"
thiserror = "1.0.34"
tsu = "1.0.1"
bytes = "1.4.0"
parking_lot = "0.12.1"
base64 = "0.21.7"
bigdecimal = "0.4"

# Note: the BEGIN and END comments below are required for external tooling. Do not remove.
# BEGIN MOVE DEPENDENCIES

# move-abigen = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-bytecode-utils = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-errmapgen = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-ir-compiler = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-prover-test-utils = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-stackless-bytecode-interpreter = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# move-transactional-test-runner = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# read-write-set = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
# read-write-set-dynamic = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-binary-format = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-bytecode-verifier = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-cli = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-command-line-common = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-compiler = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-core-types = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-docgen = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-model = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-package = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-prover = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-prover-boogie-backend = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-prover-bytecode-pipeline = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-resource-viewer = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-stackless-bytecode = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-stdlib = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-symbol-pool = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-unit-test = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-vm-runtime = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-vm-test-utils = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }
move-vm-types = { git = "https://github.com/initia-labs/move.git", rev = "1f87f9bac32707e940603e2b8b2cfddf17bc70ab" }


# END MOVE DEPENDENCIES
